openapi: 3.1.0
info:
  version: 1.0.0
  title: <Contacts>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <This is a documentation of contacts app>
tags:
  - name: Contacts
  - discription: Operations about contacts.
  - name: Auth
  - discription: Auth operations.
servers:
  - url: http://localhost:3000

  - url: #посилання на задеплоєний сайт
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
